### ISSUE TITLE
Security Breach on lighttpd

### ISSUE THREAD

**Issue by westongpt** [jinzora/jinzora3#3]
I am running lighted with php-fastcgi and mysql, after setup I get a message that says security breach. is there a way to get past it? how can i find out what causes it?

**Comment by bjdodson** [comment]
The message tells you to delete the "install" directory to avoid a security
breach.

**Comment by westongpt** [comment]
http://cl.ly/image/2h0T1f0J3Q3h <-- actually it just says security breach detected.

EDIT:
However, I did remove the install directory after you mentioned it and it still says "Security Breach Detected"

**Comment by westongpt** [comment]
not sure what I did, but I re-cloned 2 times and it finally worked on the 3rd try

**Comment by bjdodson** [comment]
Ah, interesting. Not sure why it's doing that, I'm guessing there's
something wrong with your paths? I haven't seen that issue before. What's
the url you're hitting?
